01-create-namespace:
	kubectl create namespace 04--namespace-cli

02-apply-namespace:
	kubectl apply -f Namespace.yaml

03-delete-namespaces:
	kubectl delete namespace 04--namespace-cli
	kubectl delete -f Namespace.yaml
